#!/usr/bin/env python
"""
Test suite demonstrating the meaningful data generated by refactored tools.
Shows real examples of structured analysis, metrics, and insights.
"""

import json
from decimal import Decimal

# Import refactored tools
from tools.review_tools import (
    SeverityLevel, ReviewIssue, detect_hardcoded_values, 
    check_error_handling, check_architecture_issues
)
from tools.formatting_tools import (
    analyze_line_lengths, check_indentation_consistency,
    analyze_naming_conventions, detect_code_duplication
)
from tools.validation_tools import (
    validate_pr_title, validate_pr_description, 
    validate_csharp_file_structure, validate_test_structure
)
from tools.scoring_tools import score_pr_structured, format_score_report


def test_data_models():
    """Demonstrate rich structured data models."""
    print("╔════════════════════════════════════════════════════════════════╗")
    print("║         📊 MEANINGFUL DATA MODELS & STRUCTURES                 ║")
    print("╚════════════════════════════════════════════════════════════════╝\n")
    
    # Example: ReviewIssue with all fields populated
    issue = ReviewIssue(
        file="Controllers/MoviesController.cs",
        line_number=42,
        severity=SeverityLevel.HIGH,
        category="Error Handling",
        description="Direct list access without bounds checking",
        suggestion="Check Count before accessing by index: if (movies.Count > id) { ... }",
        code_snippet="var movie = movies[id];  // Could throw IndexOutOfRangeException"
    )
    
    print("Example ReviewIssue Data:")
    print(f"  File: {issue.file}:{issue.line_number}")
    print(f"  Severity: {issue.severity.value}")
    print(f"  Category: {issue.category}")
    print(f"  Description: {issue.description}")
    print(f"  Suggestion: {issue.suggestion}")
    print(f"  Code: {issue.code_snippet}")
    print()


def test_validation_tools():
    """Test validation tools with meaningful output."""
    print("\n╔════════════════════════════════════════════════════════════════╗")
    print("║           ✔️ VALIDATION OUTPUT - DETAILED FEEDBACK             ║")
    print("╚════════════════════════════════════════════════════════════════╝\n")
    
    # Test 1: Valid title
    print("🔍 TEST 1: Valid PR Title")
    title_result = validate_pr_title("feat(movies): add genre filtering capability")
    print(f"  Title: 'feat(movies): add genre filtering capability'")
    print(f"  Valid: {title_result.is_valid}")
    print(f"  Score: {title_result.score}/10")
    print(f"  Message: {title_result.message}")
    print()
    
    # Test 2: Invalid title
    print("🔍 TEST 2: Invalid PR Title")
    bad_title = validate_pr_title("added movie feature")
    print(f"  Title: 'added movie feature'")
    print(f"  Valid: {bad_title.is_valid}")
    print(f"  Score: {bad_title.score}/10")
    print(f"  Violations:")
    for v in bad_title.violations:
        print(f"    - {v}")
    print(f"  Suggestions:")
    for s in bad_title.suggestions:
        print(f"    → {s}")
    print()
    
    # Test 3: PR Description validation
    print("🔍 TEST 3: PR Description Quality")
    description = """
    This PR adds filtering capability to movies endpoints
    
    ## What
    Added MovieFilter class with Genre, YearRange, RatingMin support
    
    ## Why  
    Users requested ability to filter movies by genre and rating
    
    ## Testing
    1. Build: dotnet build
    2. Test: dotnet test
    3. Manual: curl 'http://localhost:5000/api/movies?genre=Action'
    """
    
    desc_result = validate_pr_description(description)
    print(f"  Valid: {desc_result.is_valid}")
    print(f"  Score: {desc_result.score}/10")
    print(f"  Message: {desc_result.message}")
    print()


def test_code_analysis():
    """Test code analysis tools."""
    print("\n╔════════════════════════════════════════════════════════════════╗")
    print("║         📈 CODE ANALYSIS - FORMATTING & QUALITY METRICS        ║")
    print("╚════════════════════════════════════════════════════════════════╝\n")
    
    # Sample C# code
    sample_code = """using System;
using System.Collections.Generic;
using System.Linq;
using MovieApi.Models;

namespace MovieApi.Services
{
    public class MovieService
    {
        private readonly List<Movie> _movies = new();
        private string ApiKey = "hardcoded_key_12345";  // SECURITY ISSUE!
        
        public MovieService()
        {
            _movies.Add(new Movie { Id = 1, Title = "Die Hard", Genre = "Action" });
            _movies.Add(new Movie { Id = 2, Title = "Inception", Genre = "SciFi" });
        }
        
        // Missing null check - ISSUE!
        public Movie GetMovieById(int id)
        {
            return _movies[id];
        }
        
        public List<Movie> FilterByGenre(string genreName)
        {
            if (genreName == null) throw new ArgumentNullException(nameof(genreName));
            return _movies.Where(m => m.Genre == genreName).ToList();
        }
    }
}
"""
    
    print("Analyzing sample C# code...\n")
    
    # Line length analysis
    print("📏 LINE LENGTH ANALYSIS:")
    line_metrics = analyze_line_lengths(sample_code, max_length=120)
    print(f"  Total Lines: {line_metrics['total_lines']}")
    print(f"  Average Length: {line_metrics['average_length']:.1f} chars")
    print(f"  Max Length: {line_metrics['max_length']} chars")
    print(f"  Violations: {line_metrics['violation_count']}")
    print(f"  Compliance: {line_metrics['compliance_percentage']:.1f}%")
    print()
    
    # Indentation analysis
    print("📐 INDENTATION CONSISTENCY:")
    indent_metrics = check_indentation_consistency(sample_code)
    print(f"  Lines Checked: {indent_metrics['total_checked']}")
    print(f"  Issues Found: {indent_metrics['issue_count']}")
    print(f"  Consistency Score: {indent_metrics['consistency_score']:.1f}%")
    print()
    
    # Naming conventions
    print("🔤 NAMING CONVENTIONS:")
    naming_metrics = analyze_naming_conventions(sample_code, language="csharp")
    print(f"  Violations: {naming_metrics['violation_count']}")
    print(f"  Quality Score: {naming_metrics['quality_score']:.0f}/100")
    for v in naming_metrics['violations'][:2]:
        print(f"    - {v['issue']} → {v['suggestion']}")
    print()
    
    # Hardcoded values detection
    print("⚠️ HARDCODED VALUES DETECTED:")
    hardcode_issues = detect_hardcoded_values(sample_code, "MovieService.cs")
    print(f"  Total Issues: {len(hardcode_issues)}")
    for issue in hardcode_issues[:2]:
        print(f"    - Line {issue.line_number}: {issue.description}")
        print(f"      Suggestion: {issue.suggestion}")
    print()
    
    # Error handling analysis
    print("🛡️ ERROR HANDLING REVIEW:")
    error_issues = check_error_handling(sample_code, "MovieService.cs")
    print(f"  Issues Found: {len(error_issues)}")
    for issue in error_issues[:2]:
        print(f"    - {issue.description}")
        print(f"      Severity: {issue.severity.value}")
    print()


def test_scoring_system():
    """Test comprehensive PR scoring."""
    print("\n╔════════════════════════════════════════════════════════════════╗")
    print("║        🎯 WEIGHTED SCORING SYSTEM - MULTI-DIMENSIONAL          ║")
    print("╚════════════════════════════════════════════════════════════════╝\n")
    
    # Scenario 1: Good PR
    print("SCENARIO 1: High-Quality PR")
    print("-" * 50)
    score1 = score_pr_structured(
        title_valid=True,
        has_tests=True,
        hardcoded_issues=0,
        critical_issues=0,
        high_issues=0,
        medium_issues=1,
        architecture_score=9.0,
        code_quality_score=8.5,
        security_score=9.5,
        documentation_quality=True,
        pr_size_lines=180
    )
    
    print(f"Overall Score: {score1.overall_score}/10")
    print(f"Recommendation: {score1.recommendation.value}")
    print("\nMetric Breakdown:")
    for metric in score1.metrics:
        pct = (metric.score / metric.max_score * 100) if metric.max_score > 0 else 0
        print(f"  {metric.name}: {metric.score}/10 ({pct:.0f}%) - Weight: {metric.weight*100:.0f}%")
    
    if score1.blockers:
        print("\nBlockers:")
        for b in score1.blockers:
            print(f"  {b}")
    
    if score1.improvements:
        print("\nImprovements:")
        for i in score1.improvements:
            print(f"  {i}")
    print()
    
    # Scenario 2: Poor PR
    print("\nSCENARIO 2: Poor-Quality PR Requiring Changes")
    print("-" * 50)
    score2 = score_pr_structured(
        title_valid=False,
        has_tests=False,
        hardcoded_issues=2,
        critical_issues=1,
        high_issues=3,
        medium_issues=5,
        architecture_score=4.0,
        code_quality_score=5.0,
        security_score=3.0,
        documentation_quality=False,
        pr_size_lines=650
    )
    
    print(f"Overall Score: {score2.overall_score}/10")
    print(f"Recommendation: {score2.recommendation.value}")
    print("\nMetric Breakdown:")
    for metric in score2.metrics:
        pct = (metric.score / metric.max_score * 100) if metric.max_score > 0 else 0
        bar = "█" * int(pct / 10) + "░" * (10 - int(pct / 10))
        print(f"  {metric.name}: {metric.score:>4.1f}/10 [{bar}]")
    
    print("\nBlockers (MUST FIX):")
    for b in score2.blockers:
        print(f"  {b}")
    
    print("\nRequired Improvements:")
    for i in score2.improvements[:3]:
        print(f"  {i}")
    print()


def test_report_generation():
    """Test report generation."""
    print("\n╔════════════════════════════════════════════════════════════════╗")
    print("║          📋 GENERATED REPORT - HUMAN-READABLE OUTPUT           ║")
    print("╚════════════════════════════════════════════════════════════════╝\n")
    
    score = score_pr_structured(
        title_valid=True,
        has_tests=True,
        hardcoded_issues=1,
        critical_issues=0,
        high_issues=1,
        medium_issues=2,
        architecture_score=7.5,
        code_quality_score=7.0,
        security_score=8.0,
        documentation_quality=True,
        pr_size_lines=245
    )
    
    report = format_score_report(score)
    print(report)


def main():
    """Run all tests."""
    test_data_models()
    test_validation_tools()
    test_code_analysis()
    test_scoring_system()
    test_report_generation()
    
    print("\n" + "="*66)
    print("✅ ALL TESTS COMPLETED - MEANINGFUL DATA SUCCESSFULLY GENERATED")
    print("="*66 + "\n")
    
    print("📊 Key Takeaways:")
    print("  • Rich data models with type safety and structure")
    print("  • Severity levels for better issue prioritization")
    print("  • Weighted multi-dimensional scoring (not just 1-10)")
    print("  • Line-specific issue citations for code review")
    print("  • Structured validation with detailed feedback")
    print("  • Code quality metrics with percentage scores")
    print("  • Human-readable reports from structured data")
    print("  • JSON serializable for automation/CI integration")
    print()


if __name__ == "__main__":
    main()
